name: Deploy to GitHub Pages via angular-cli-ghpages

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 20.x
        uses: actions/setup-node@v1
        with:
          node-version: 20.x

      - name: Prepare and deploy
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npm ci --legacy-peer-deps
          npm run lint
          npx angular-cli-ghpages --dir=dist/moviengine --name="Sofiia Anenko" --email=anenko.sofiia@gmail.com

